[[headers]]
  for = "/api/*"
  [headers.values]
  Access-Control-Allow-Origin = "https://ivylearner.netlify.app"
  Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
  Access-Control-Allow-Headers = "Content-Type, Authorization"
  Access-Control-Allow-Credentials = "true"
